name: Map Distance
options:
  bundleIdPrefix: io.adrimi
packages:
  ViewInspector:
    url: https://github.com/nalexn/ViewInspector.git
    from: 0.3.12
targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "13.2"
    sources: [MyApp]
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: my_debug_value
        release:
          CUSTOM_BUILD_SETTING: my_release_value
    dependencies:
      - package: ViewInspector
    settings:
      base:
        SWIFT_VERSION: "5"