name: Map Distance
options:
  bundleIdPrefix: io.adrimi

packages:
  ViewInspector:
    url: https://github.com/nalexn/ViewInspector.git
    from: 0.3.12

targets:
  Map Distance:
    type: application
    platform: iOS
    deploymentTarget: "13.2"
    sources: Map Distance
    settings:
      base:
        SWIFT_VERSION: "5"
      configs:
        Debug:
          DEBUG_MODE: YES
          Debug Information Format: dwarf-with-dsym
        Release:
          DEBUG_MODE: NO
    scheme:
      testTargets:
        - Map DistanceTests
    postBuildScripts:
      - script: "${PODS_ROOT}/FirebaseCrashlytics/run"
        name: Crashlytics
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)

  Map DistanceTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "13.2"
    sources: Map DistanceTests
    dependencies:
      - target: Map Distance
      - package: ViewInspector
