desc "Create on Developer portal and App Store Connect"
lane :create_app do
  create_app_online #produce
end

platform :ios do
  desc "Sync signing"
  lane :signing do
    sync_code_signing  #match
  end

  desc "Build binary"
  lane :build do
    signing
  end

  desc "Release"
  lane :release do
    build
  end
end
